# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58bc7e61a86484d3c4702df8bf7c882da01f90ef2fe7d37fb2347b51bc2714185e44342fd4cd94aa19ea114bd04657b031711c9645ea40a7be0b527785704002

test:
  secret_key_base: ee0fa60876b9c9117528b2b734cabb6818b794bd53cc046511b21e0221832b1bf0b932efb1076d8510c6aed25eff184e486fcec19abd2fddeb96bbcbb369abbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
